config/routes.rb
Rails.application.routes.draw do
  root "sessions#home"

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  #login route 1. to display the log in 2. to process the log in
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/auth/facebook/callback' => 'sessions#create'
  
  
  #logout route
  delete '/logout' => 'sessions#destroy'
 
  
  resources :locations do
    resources :appointments, only: [:new, :show, :index]
  end

  resources :clients do 
     resources :appointments, only: [:new, :show, :index]
  end

  resources :users do 
    resources :appointments, only: [:new, :create, :index]
  end

  resources :appointments 


end

app/models/user.rb
class User < ApplicationRecord
has_many :clients, dependent: :destroy  
has_many :appointments, dependent: :destroy  
has_many :locations, dependent: :destroy  
has_secure_password
end



#'/users'

#'/users/:id/appointments'
#'/users/:id/clients'
#'/users/:id/locations'


#'/appointments'

#'/appointments/:id/clients'
#'/appointments/:id/locations'

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new 
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user_id
            redirect_to user_path(@user) 
        else 
            render :new
        end
    end
    

    def show
        redirect_if_not_logged_in
        @user = User.find_by_id(params[:id])
    end

    def update
        @user = User.find_by_id(params[:id])
        @user.update_columns(username: params[:user][:username],
        email: params[:user][:email])
        redirect_to user_path(@user)
    end

    def index
        @user = User.find_by_id(params[:id]) 
    end

    def destroy 
        @user = current_user.destroy
        session.clear
        redirect_to root_path
    end

  

    private

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end




end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<br>
<h1>Edit Your Account</h1>
<br>

<div>
<ul>
<%= form_for(current_user) do |f| %>

   <li> 
    <%=  f.label :username %>
    <%=  f.text_field :username, required:true %>
    </li>
        <br>
        <br>
    <li>
    <%=  f.label :email %>
    <%=  f.email_field :email, required:true%>
    </li>
        <br>
        <br>

    <%=  f.submit "Save" %>

    <%end%>
</ul>
</div>

  <%= link_to "Delete", current_user, method: :delete, data: { confirm: "Are you sure you want to delete your account?" } %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for(@user) do |f| %>
    <%=  f.label :username %>
    <%=  f.text_field :username %>
        <br>
        <br>
    <%=  f.label :email %>
    <%=  f.email_field :email, required:true%>
        <br>
        <br>
    <%=  f.label :password %>
    <%=  f.password_field :password %>
        <br>
        <br>

    <%=  f.submit "Submit" %>


<% end %>

app/views/users/show.html.erb
 <br>
 <h1>Welcome <%=current_user.username%></h1>
 <h5><%=current_user.email%></h5>
    <br>

    <br>
<div>
<h3> Clients and Locations </h3>
<br>
<body>
<ul>
    <% current_user.appointments.each do |a|%>
      <li><%= link_to a.client.name, client_path(a) %> | <%= link_to a.location.nickname, location_path(a)%> </li><br>
    <% end %>
</ul>
</body>
</div>

<br>

<%= link_to "Edit User Account", edit_user_path(:user_id)%>