config/routes.rb
Rails.application.routes.draw do
  root "sessions#home"

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  #login route 1. to display the log in 2. to process the log in
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/auth/facebook/callback' => 'sessions#create'
  
  
  #logout route
  delete '/logout' => 'sessions#destroy'
 
  
  resources :locations do
    resources :appointments, only: [:new, :show, :index]
  end

  resources :clients do 
     resources :appointments, only: [:new, :show, :index]
  end

  resources :users do 
    resources :appointments, only: [:new, :create, :index]
  end

  resources :appointments 


end

app/models/client.rb
class Client < ApplicationRecord
    belongs_to :user
    has_many :appointments, dependent: :destroy
    has_many :locations, through: :appointments
    validates_presence_of :name
    validates_presence_of :phone_number
    validates_presence_of :email
    end

    

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

    
    def index
        if params[:appointment_id]
            @clients = @user.clients
        else
            @clients = current_user.clients.all
        end   
    end
    
    def new 
        @client = Client.new
    end
    
    def create 
        @client = current_user.clients.build(client_params)
        if @client.save 
            redirect_to clients_path
        else 
            render :new
        end
    end

    def edit
        @client = current_user.clients.find(params[:id])
    end

    def update
        @client = current_user.clients.find(params[:id])
        if @client.update(client_params)
            redirect_to @client
        else
            render :edit
        end
    end

    def show
        redirect_if_not_logged_in
        @client = current_user.clients.find_by_id(params[:id])
    end

    private

    def client_params
        params.require(:client).permit(:user_id, :name, :phone_number, :email)
    end



end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_clients.html.erb
<ul>
    <% @clients.each do |c|%>
      <li><%= link_to c.name, client_path(c) %> </li><br>
    <% end %>
</ul>

app/views/clients/_form.html.erb
<%= form_for @client do |client| %>
  
  <%= client.hidden_field :user_id, :value => current_user.id %>
  <h5>Client Information</h5>
  <br>

  <li>
      <%= client.label :name, "Name:" %>
      <%= client.text_field :name %>
      <%= error_messages_for(client.object, :name)%>
  </li>
      <br>
  <li>  
      <%= client.label :phone_number, "Number:" %>
      <%= client.telephone_field :phone_number %>
      <%= error_messages_for(client.object, :phone_number)%>
  </li>
      <br>
  <li>    
      <%= client.label :email, "Email:" %>
      <%= client.email_field :email %>
      <%= error_messages_for(client.object, :email)%>
  </li>

  <%= client.submit %>
<% end %>

app/views/clients/edit.html.erb
<br>
<h1>Edit Client </h1>

<%= render "form" %>

app/views/clients/index.html.erb
<br>
<h1>All Clients</h1>
<br>

<br>

 <%= render partial: "clients", locals: {clients: @clients} %>

app/views/clients/show.html.erb
<br>
<h1>Client Information For The Trainer</h1>

<body>
<p>This will show the trainer stats on the clients past appointments</p>
<p>This will show the trainer health stats on the client</p>
    <ol>
    <li> Health Stats </li>
    <li> Appointment Stats </li>
    <li> Goals for Client </li>
    <li> Current Training Program </li>
    </ol>
</body>

<% if @client%>
   
   <%=link_to "New Session with #{@client.name}", new_client_appointment_path(@client)%>

<%elsif @location%>
   
   <%=link_to "New Session at #{@location.nickname}", new_location_appointment_path(@location)%>

<%end%>

|

<%= link_to "Edit Client", edit_client_path(@client) %>