config/routes.rb
Rails.application.routes.draw do
  root "sessions#home"

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  #login route 1. to display the log in 2. to process the log in
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/auth/facebook/callback' => 'sessions#create'
  
  
  #logout route
  delete '/logout' => 'sessions#destroy'
 
  
  resources :locations do
    resources :appointments, only: [:new, :show, :index]
  end

  resources :clients do 
     resources :appointments, only: [:new, :show, :index]
  end

  resources :users do 
    resources :appointments, only: [:new, :create, :index]
  end

  resources :appointments 


end

app/models/appointment.rb
class Appointment < ApplicationRecord
    belongs_to :location
    belongs_to :user
    belongs_to :client
    
    accepts_nested_attributes_for :client
    accepts_nested_attributes_for :location


    def client_attributes=(attributes)
        if client = Client.find_by_id(attributes[:id])
            client.assign_attributes(attributes)
        else
            client = Client.new(attributes)  
        end
            client.appointments << self 
    end

    def location_attributes=(attributes)
        if location = Location.find_by(id: attributes[:id])
            location.assign_attributes(attributes)
        else
            location = Location.new(attributes)
        end
            location.appointments << self
    end


    scope :alpha, -> { includes(:client).order('clients.name') }

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
    
    #before_action :redirect_if_not_logged_in
    before_action :current_user

    def new
        if params[:user_id] && @user = User.find_by_id(params[:user_id])
            @appointment = @user.appointments.build
        elsif params[:client_id] && @client = current_user.clients.find_by(id: params[:client_id])
            @appointment = @client.appointments.build
        elsif params[:location_id] && @location = current_user.locations.find_by(id: params[:location_id])
            @appointment = @location.appointments.build
        else
            @appointment = Appointment.new
        end
    end


    def index
        if params[:user_id] && @user = User.find_by_id(params[:user_id])
            @appointments = @user.appointments.alpha
        elsif params[:client_id] && @client = Client.find_by_id(params[:client_id])
            @appointments = @client.appointments.order(:date)
        elsif params[:location_id] && @location = Location.find_by_id(params[:location_id])
            @appointments = @location.appointments
        else
            @appointments = current_user.appointments.alpha
        end
        
    end

    
    def create
        @appointment = current_user.appointments.build(appointment_params)
        if @appointment.save
            redirect_to appointments_path
        else
            render :new
        end
    end

    def edit
        @appointment = Appointment.find_by_id(params[:id])
        redirect_to appointments_path if !@appointment || @appointment.user != current_user
    end

    def show
        @appointment = Appointment.find_by_id(params[:id])
    end

    def update 
        @appointment = Appointment.find_by_id(params[:id])
        redirect_to to appointments_path if !@appointment || @appointment.user != current_user
        if @appointment.update(appointment_params)
            redirect_to appointment_path(@appointment)
        else
            render :edit
        end
    end

    def destroy 
        @appointment = Appointment.destroy(params[:id])
        redirect_to appointments_path
    end

    private

    def appointment_params
        params.require(:appointment).permit(:user_id,:time,:date,:price, client_attributes:[:user_id, :name, :phone_number, :email, :id], location_attributes:[:user_id, :nickname, :city, :street_address, :state, :zipcode, :id])
    end

end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_appointments.html.erb
<ul>
    <% @appointments.each do |a|%>
      <li><%= link_to a.client.name, client_appointments_path(a.client) %> | <%= link_to a.location.nickname, location_appointments_path(a.location)%> | <%= link_to a.date, appointment_path(a)%></li><br>
    <% end %>
</ul>

app/views/appointments/_client_fields.html.erb
<%= f.fields_for :client, f.object.client || Client.new do |client_attributes|%>
  <%= client_attributes.hidden_field :user_id, :value => current_user.id, disabled: disabled %>
  <h5>Client Information</h5>
  <br>

  <li>
      <%= client_attributes.label :name, "Name:" %>
      <%= client_attributes.text_field :name %>
    </li>
      <br>
  <li>  
      <%= client_attributes.label :phone_number, "Number:" %>
      <%= client_attributes.telephone_field :phone_number %>
    </li>
      <br>
  <li>    
      <%= client_attributes.label :email, "Email:" %>
      <%= client_attributes.email_field :email %>
    </li>
  <% end %>

app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>

<ul>
<body>
    <%= render 'client_fields', f: f, disabled: params[:action] == 'new' && params[:client_id] %>
    <br>

    <%= render 'location_fields', f: f, disabled: params[:action] == 'new' && params[:location_id] %>

    <h5>Session Information</h5>
    <li>
        <%= f.label :time %>
        <%= f.time_field :time %>
    </li>
        <br>
    <li>
        <%= f.label :date %>
        <%= f.date_field :date %>    
    </li>
        <br>
    <li>
        <%= f.label :price %>
        <%= f.number_field :price %>
    </li>
        <br>
    <%= f.hidden_field :user_id, :value => current_user.id %>

    <%= f.submit %>
</body>    
<ul> 
<% end %>

app/views/appointments/_location_fields.html.erb
<%= f.fields_for :location, f.object.location || Location.new do |location_attributes|%>
    <%= location_attributes.hidden_field :user_id, :value => current_user.id, disabled: disabled%>
    <h5>Location Information</h5>
    <br>

    <li>
        <%= location_attributes.label :nickname, "Nickname:" %>
        <%= location_attributes.text_field :nickname, disabled: disabled %>
    </li>
        <br>
    <li>  
        <%= location_attributes.label :city, "City:" %>
        <%= location_attributes.text_field :city, disabled: disabled %>
    </li>
        <br>
    <li>    
        <%= location_attributes.label :street_address, "Street Address:" %>
        <%= location_attributes.text_field :street_address, disabled: disabled %>
    </li>
    <br>
    <li>  
        <%= location_attributes.label :state, "State:" %>
        <%= location_attributes.text_field :state, disabled: disabled %>
    </li>
        <br>
    <li>  
        <%= location_attributes.label :zipcode, "Zipcode:" %>
        <%= location_attributes.text_field :zipcode, disabled: disabled %>
    </li>
        <br>
<% end %>

app/views/appointments/edit.html.erb
<h1>Edit Session With <%= @appointment.client.name%></h1>

<%= render 'form' %>

 <p>
      <%= link_to "Delete", @appointment, method: :delete, data: { confirm: "Are you sure you want to delete this appointment?" } %>

app/views/appointments/index.html.erb
   <br>
 <h2>Upcomming Sessions</h2>
   <br>


 <%= render partial: "appointments", locals: {appointments: @appointments} %>

   <% if @client%>
   
<%=link_to "New Session with #{@client.name}", new_client_appointment_path(@client)%>

   <%elsif @location%>
   
<%=link_to "New Session at #{@location.nickname}", new_location_appointment_path(@location)%>

<%end%>

app/views/appointments/new.html.erb
<br>
<h1>New Session</h1>
<br>

<%= render 'form' %>

app/views/appointments/show.html.erb
 <br>
 <h2>Session For <%=@appointment.client.name%></h2>
<br>



<h5><%=link_to @appointment.client.name, client_path%></h5>
<h5><%=link_to @appointment.location.nickname, location_path%> </h5>
<h5><%=link_to @appointment.date, edit_appointment_path(@appointment)%> </h5>
<h5><%=link_to @appointment.price, edit_appointment_path(@appointment)%> </h5>

<br>
 <%= link_to "Edit Hoop Session", edit_appointment_path(@appointment)%>
<br>
 <body>
 <br>
 <p>This will show the client all this specefic session information.</p>
 </body>
 <ol>
 <li>Health Stats</li>
 <li>Pictures and Vidoes</li>
 <li>Notes</li>
 <li>goals</li>

 