config/routes.rb
Rails.application.routes.draw do
  root "sessions#home"

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  #login route 1. to display the log in 2. to process the log in
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/auth/facebook/callback' => 'sessions#create'
  
  
  #logout route
  delete '/logout' => 'sessions#destroy'
 
  
  resources :locations do
    resources :appointments, only: [:new, :show, :index]
  end

  resources :clients do 
     resources :appointments, only: [:new, :show, :index]
  end

  resources :users do 
    resources :appointments, only: [:new, :create, :index]
  end

  resources :appointments 


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BasketballTrainerManagement</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootswatch/4.5.2/lux/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="#">Basketball Client Management</a>
  </nav>




    <div>
      <%if logged_in?%>
      <%= link_to 'Home', user_path(:user_id) %> |
      <%= link_to 'New Session', new_appointment_path %> |
      <%= link_to 'View Sessions', appointments_path %> |
      <%= link_to 'View Clients', clients_path %> |
      <%= link_to 'View Locations', locations_path %> |
      <%= link_to "Logout", logout_path, method: "delete" %> 
     


      <%else%>
      <%= link_to 'Sign Up', signup_path %> |
      <%= link_to 'Sign In', login_path %> |
      <%= link_to 'Sign In with Facebook', '/auth/facebook' %>
      <% end %>

      </div>
    <%= yield %>
  </body>
</html>